import { useMutation, useQueryClient } from "@tanstack/react-query";
import { useServerFn } from "@tanstack/react-start";
import { useState } from "react";
import { toast } from "sonner";

import { Button } from "@/components/ui/button";
import { Checkbox } from "@/components/ui/checkbox";
import { Dialog, DialogContent, DialogDescription, DialogFooter, DialogHeader, DialogTitle } from "@/components/ui/dialog";
import { Input } from "@/components/ui/input";
import { Select, SelectContent, SelectItem, SelectTrigger, SelectValue } from "@/components/ui/select";
import { applyProductSaleUnitBatch } from "@/lib/sales-units.functions";
import type { CompanyUnit } from "./sales-unit-manager";

type Operation = "add" | "visible_on" | "visible_off" | "active_on" | "active_off" | "factor" | "default" | "remove";
export function SalesUnitBatchDialog({ open, onOpenChange, companyId, productIds, units }: { open: boolean; onOpenChange: (open: boolean) => void; companyId: string; productIds: string[]; units: CompanyUnit[] }) {
  const run = useServerFn(applyProductSaleUnitBatch); const queryClient = useQueryClient();
  const [unitId, setUnitId] = useState(""); const [operation, setOperation] = useState<Operation>("add"); const [factor, setFactor] = useState(""); const [overwrite, setOverwrite] = useState(false); const [confirmed, setConfirmed] = useState(false);
  const mutation = useMutation({ mutationFn: () => { const mapped = operation.startsWith("visible") ? "visible" : operation.startsWith("active") ? "active" : operation; return run({ data: { companyId, productIds, unitId, operation: mapped, booleanValue: operation.endsWith("_on") ? true : operation.endsWith("_off") ? false : null, conversionFactor: operation === "factor" && factor ? Number(factor.replace(",", ".")) : null, overwrite } }); }, onSuccess: async (result) => { await queryClient.invalidateQueries({ queryKey: ["product-sale-units", companyId] }); toast.success(`Aggiornati ${result.changed} prodotti`, { description: `${result.unchanged} invariati.` }); onOpenChange(false); }, onError: (error: Error) => toast.error(error.message) });
  const labels: Record<Operation,string> = { add:"Aggiungi se assente", visible_on:"Rendi visibile al cliente", visible_off:"Nascondi al cliente", active_on:"Attiva", active_off:"Disattiva", factor:"Imposta conversione stimata", default:"Imposta come predefinita", remove:"Rimuovi associazione mai usata" };
  return <Dialog open={open} onOpenChange={(next) => { onOpenChange(next); if (!next) setConfirmed(false); }}><DialogContent><DialogHeader><DialogTitle>Gestisci U.M. vendita</DialogTitle><DialogDescription>L’operazione riguarda {productIds.length} prodotti selezionati e non modifica i dati Danea.</DialogDescription></DialogHeader><div className="space-y-4"><Select value={unitId} onValueChange={setUnitId}><SelectTrigger><SelectValue placeholder="Scegli U.M." /></SelectTrigger><SelectContent>{units.filter((u) => u.status === "attivo").map((u) => <SelectItem key={u.id} value={u.id}>{u.code} — {u.description}</SelectItem>)}</SelectContent></Select><Select value={operation} onValueChange={(value) => { setOperation(value as Operation); setConfirmed(false); }}><SelectTrigger><SelectValue /></SelectTrigger><SelectContent>{Object.entries(labels).map(([value,label]) => <SelectItem key={value} value={value}>{label}</SelectItem>)}</SelectContent></Select>{operation === "factor" ? <><Input aria-label="Fattore stimato" inputMode="decimal" placeholder="Es. 15" value={factor} onChange={(e) => setFactor(e.target.value)} /><label className="flex items-center gap-2 text-sm"><Checkbox checked={overwrite} onCheckedChange={(v) => setOverwrite(v === true)} />Sovrascrivi anche le conversioni già presenti</label></> : null}<div className="rounded-md border border-border bg-muted p-3 text-sm"><strong>Anteprima</strong><p className="mt-1">{labels[operation]} su {productIds.length} prodotti. Le configurazioni non interessate restano invariate.</p></div><label className="flex items-start gap-2 text-sm"><Checkbox checked={confirmed} onCheckedChange={(v) => setConfirmed(v === true)} />Confermo l’operazione sui prodotti selezionati.</label></div><DialogFooter><Button variant="outline" onClick={() => onOpenChange(false)}>Annulla</Button><Button disabled={!unitId || !confirmed || mutation.isPending || (operation === "factor" && (!factor || Number(factor.replace(",", ".")) <= 0))} onClick={() => mutation.mutate()}>{mutation.isPending ? "Applicazione…" : "Applica"}</Button></DialogFooter></DialogContent></Dialog>;
}