/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as ResetPasswordRouteImport } from './routes/reset-password'
import { Route as AuthenticatedAccountRouteImport } from './routes/_authenticated/account'
import { Route as AuthenticatedAmministrazioneRouteImport } from './routes/_authenticated/amministrazione'
import { Route as AuthenticatedConsegneRouteImport } from './routes/_authenticated/consegne'
import { Route as AuthenticatedDaneaRouteImport } from './routes/_authenticated/danea'
import { Route as AuthenticatedDashboardRouteImport } from './routes/_authenticated/dashboard'
import { Route as AuthenticatedOnboardingRouteImport } from './routes/_authenticated/onboarding'
import { Route as AuthenticatedOperativoRouteImport } from './routes/_authenticated/operativo'
import { Route as AuthenticatedVenditeRouteImport } from './routes/_authenticated/vendite'
import { Route as InvitoTokenRouteImport } from './routes/invito.$token'
import { Route as AuthenticatedAcquistiIndexRouteImport } from './routes/_authenticated/acquisti.index'
import { Route as AuthenticatedAcquistiFornitoriRouteImport } from './routes/_authenticated/acquisti.fornitori'
import { Route as AuthenticatedVenditeClientiRouteImport } from './routes/_authenticated/vendite_.clienti'
import { Route as AuthenticatedVenditeProdottiRouteImport } from './routes/_authenticated/vendite_.prodotti'
import { Route as ApiPublicDaneaProductsRouteImport } from './routes/api/public/danea/products'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const ResetPasswordRoute = ResetPasswordRouteImport.update({
  id: '/reset-password',
  path: '/reset-password',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedAccountRoute = AuthenticatedAccountRouteImport.update({
  id: '/account',
  path: '/account',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedAmministrazioneRoute =
  AuthenticatedAmministrazioneRouteImport.update({
    id: '/amministrazione',
    path: '/amministrazione',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedConsegneRoute = AuthenticatedConsegneRouteImport.update({
  id: '/consegne',
  path: '/consegne',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedDaneaRoute = AuthenticatedDaneaRouteImport.update({
  id: '/danea',
  path: '/danea',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedDashboardRoute = AuthenticatedDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedOnboardingRoute = AuthenticatedOnboardingRouteImport.update({
  id: '/onboarding',
  path: '/onboarding',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedOperativoRoute = AuthenticatedOperativoRouteImport.update({
  id: '/operativo',
  path: '/operativo',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedVenditeRoute = AuthenticatedVenditeRouteImport.update({
  id: '/vendite',
  path: '/vendite',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const InvitoTokenRoute = InvitoTokenRouteImport.update({
  id: '/invito/$token',
  path: '/invito/$token',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedAcquistiIndexRoute =
  AuthenticatedAcquistiIndexRouteImport.update({
    id: '/acquisti/',
    path: '/acquisti/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedAcquistiFornitoriRoute =
  AuthenticatedAcquistiFornitoriRouteImport.update({
    id: '/acquisti/fornitori',
    path: '/acquisti/fornitori',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedVenditeClientiRoute =
  AuthenticatedVenditeClientiRouteImport.update({
    id: '/vendite_/clienti',
    path: '/vendite/clienti',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedVenditeProdottiRoute =
  AuthenticatedVenditeProdottiRouteImport.update({
    id: '/vendite_/prodotti',
    path: '/vendite/prodotti',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const ApiPublicDaneaProductsRoute = ApiPublicDaneaProductsRouteImport.update({
  id: '/api/public/danea/products',
  path: '/api/public/danea/products',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/reset-password': typeof ResetPasswordRoute
  '/account': typeof AuthenticatedAccountRoute
  '/amministrazione': typeof AuthenticatedAmministrazioneRoute
  '/consegne': typeof AuthenticatedConsegneRoute
  '/danea': typeof AuthenticatedDaneaRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/onboarding': typeof AuthenticatedOnboardingRoute
  '/operativo': typeof AuthenticatedOperativoRoute
  '/vendite': typeof AuthenticatedVenditeRoute
  '/invito/$token': typeof InvitoTokenRoute
  '/acquisti/fornitori': typeof AuthenticatedAcquistiFornitoriRoute
  '/vendite/clienti': typeof AuthenticatedVenditeClientiRoute
  '/vendite/prodotti': typeof AuthenticatedVenditeProdottiRoute
  '/acquisti/': typeof AuthenticatedAcquistiIndexRoute
  '/api/public/danea/products': typeof ApiPublicDaneaProductsRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/reset-password': typeof ResetPasswordRoute
  '/account': typeof AuthenticatedAccountRoute
  '/amministrazione': typeof AuthenticatedAmministrazioneRoute
  '/consegne': typeof AuthenticatedConsegneRoute
  '/danea': typeof AuthenticatedDaneaRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/onboarding': typeof AuthenticatedOnboardingRoute
  '/operativo': typeof AuthenticatedOperativoRoute
  '/vendite': typeof AuthenticatedVenditeRoute
  '/invito/$token': typeof InvitoTokenRoute
  '/acquisti/fornitori': typeof AuthenticatedAcquistiFornitoriRoute
  '/vendite/clienti': typeof AuthenticatedVenditeClientiRoute
  '/vendite/prodotti': typeof AuthenticatedVenditeProdottiRoute
  '/acquisti': typeof AuthenticatedAcquistiIndexRoute
  '/api/public/danea/products': typeof ApiPublicDaneaProductsRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/auth': typeof AuthRoute
  '/reset-password': typeof ResetPasswordRoute
  '/_authenticated/account': typeof AuthenticatedAccountRoute
  '/_authenticated/amministrazione': typeof AuthenticatedAmministrazioneRoute
  '/_authenticated/consegne': typeof AuthenticatedConsegneRoute
  '/_authenticated/danea': typeof AuthenticatedDaneaRoute
  '/_authenticated/dashboard': typeof AuthenticatedDashboardRoute
  '/_authenticated/onboarding': typeof AuthenticatedOnboardingRoute
  '/_authenticated/operativo': typeof AuthenticatedOperativoRoute
  '/_authenticated/vendite': typeof AuthenticatedVenditeRoute
  '/invito/$token': typeof InvitoTokenRoute
  '/_authenticated/acquisti/fornitori': typeof AuthenticatedAcquistiFornitoriRoute
  '/_authenticated/vendite_/clienti': typeof AuthenticatedVenditeClientiRoute
  '/_authenticated/vendite_/prodotti': typeof AuthenticatedVenditeProdottiRoute
  '/_authenticated/acquisti/': typeof AuthenticatedAcquistiIndexRoute
  '/api/public/danea/products': typeof ApiPublicDaneaProductsRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/reset-password'
    | '/account'
    | '/amministrazione'
    | '/consegne'
    | '/danea'
    | '/dashboard'
    | '/onboarding'
    | '/operativo'
    | '/vendite'
    | '/invito/$token'
    | '/acquisti/fornitori'
    | '/vendite/clienti'
    | '/vendite/prodotti'
    | '/acquisti/'
    | '/api/public/danea/products'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/reset-password'
    | '/account'
    | '/amministrazione'
    | '/consegne'
    | '/danea'
    | '/dashboard'
    | '/onboarding'
    | '/operativo'
    | '/vendite'
    | '/invito/$token'
    | '/acquisti/fornitori'
    | '/vendite/clienti'
    | '/vendite/prodotti'
    | '/acquisti'
    | '/api/public/danea/products'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/auth'
    | '/reset-password'
    | '/_authenticated/account'
    | '/_authenticated/amministrazione'
    | '/_authenticated/consegne'
    | '/_authenticated/danea'
    | '/_authenticated/dashboard'
    | '/_authenticated/onboarding'
    | '/_authenticated/operativo'
    | '/_authenticated/vendite'
    | '/invito/$token'
    | '/_authenticated/acquisti/fornitori'
    | '/_authenticated/vendite_/clienti'
    | '/_authenticated/vendite_/prodotti'
    | '/_authenticated/acquisti/'
    | '/api/public/danea/products'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  AuthRoute: typeof AuthRoute
  ResetPasswordRoute: typeof ResetPasswordRoute
  InvitoTokenRoute: typeof InvitoTokenRoute
  ApiPublicDaneaProductsRoute: typeof ApiPublicDaneaProductsRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reset-password': {
      id: '/reset-password'
      path: '/reset-password'
      fullPath: '/reset-password'
      preLoaderRoute: typeof ResetPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/account': {
      id: '/_authenticated/account'
      path: '/account'
      fullPath: '/account'
      preLoaderRoute: typeof AuthenticatedAccountRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/amministrazione': {
      id: '/_authenticated/amministrazione'
      path: '/amministrazione'
      fullPath: '/amministrazione'
      preLoaderRoute: typeof AuthenticatedAmministrazioneRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/consegne': {
      id: '/_authenticated/consegne'
      path: '/consegne'
      fullPath: '/consegne'
      preLoaderRoute: typeof AuthenticatedConsegneRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/danea': {
      id: '/_authenticated/danea'
      path: '/danea'
      fullPath: '/danea'
      preLoaderRoute: typeof AuthenticatedDaneaRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/dashboard': {
      id: '/_authenticated/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof AuthenticatedDashboardRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/onboarding': {
      id: '/_authenticated/onboarding'
      path: '/onboarding'
      fullPath: '/onboarding'
      preLoaderRoute: typeof AuthenticatedOnboardingRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/operativo': {
      id: '/_authenticated/operativo'
      path: '/operativo'
      fullPath: '/operativo'
      preLoaderRoute: typeof AuthenticatedOperativoRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/vendite': {
      id: '/_authenticated/vendite'
      path: '/vendite'
      fullPath: '/vendite'
      preLoaderRoute: typeof AuthenticatedVenditeRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/invito/$token': {
      id: '/invito/$token'
      path: '/invito/$token'
      fullPath: '/invito/$token'
      preLoaderRoute: typeof InvitoTokenRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/acquisti/': {
      id: '/_authenticated/acquisti/'
      path: '/acquisti'
      fullPath: '/acquisti/'
      preLoaderRoute: typeof AuthenticatedAcquistiIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/acquisti/fornitori': {
      id: '/_authenticated/acquisti/fornitori'
      path: '/acquisti/fornitori'
      fullPath: '/acquisti/fornitori'
      preLoaderRoute: typeof AuthenticatedAcquistiFornitoriRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/vendite_/clienti': {
      id: '/_authenticated/vendite_/clienti'
      path: '/vendite/clienti'
      fullPath: '/vendite/clienti'
      preLoaderRoute: typeof AuthenticatedVenditeClientiRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/vendite_/prodotti': {
      id: '/_authenticated/vendite_/prodotti'
      path: '/vendite/prodotti'
      fullPath: '/vendite/prodotti'
      preLoaderRoute: typeof AuthenticatedVenditeProdottiRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/api/public/danea/products': {
      id: '/api/public/danea/products'
      path: '/api/public/danea/products'
      fullPath: '/api/public/danea/products'
      preLoaderRoute: typeof ApiPublicDaneaProductsRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface AuthenticatedRouteRouteChildren {
  AuthenticatedAccountRoute: typeof AuthenticatedAccountRoute
  AuthenticatedAmministrazioneRoute: typeof AuthenticatedAmministrazioneRoute
  AuthenticatedConsegneRoute: typeof AuthenticatedConsegneRoute
  AuthenticatedDaneaRoute: typeof AuthenticatedDaneaRoute
  AuthenticatedDashboardRoute: typeof AuthenticatedDashboardRoute
  AuthenticatedOnboardingRoute: typeof AuthenticatedOnboardingRoute
  AuthenticatedOperativoRoute: typeof AuthenticatedOperativoRoute
  AuthenticatedVenditeRoute: typeof AuthenticatedVenditeRoute
  AuthenticatedAcquistiFornitoriRoute: typeof AuthenticatedAcquistiFornitoriRoute
  AuthenticatedVenditeClientiRoute: typeof AuthenticatedVenditeClientiRoute
  AuthenticatedVenditeProdottiRoute: typeof AuthenticatedVenditeProdottiRoute
  AuthenticatedAcquistiIndexRoute: typeof AuthenticatedAcquistiIndexRoute
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedAccountRoute: AuthenticatedAccountRoute,
  AuthenticatedAmministrazioneRoute: AuthenticatedAmministrazioneRoute,
  AuthenticatedConsegneRoute: AuthenticatedConsegneRoute,
  AuthenticatedDaneaRoute: AuthenticatedDaneaRoute,
  AuthenticatedDashboardRoute: AuthenticatedDashboardRoute,
  AuthenticatedOnboardingRoute: AuthenticatedOnboardingRoute,
  AuthenticatedOperativoRoute: AuthenticatedOperativoRoute,
  AuthenticatedVenditeRoute: AuthenticatedVenditeRoute,
  AuthenticatedAcquistiFornitoriRoute: AuthenticatedAcquistiFornitoriRoute,
  AuthenticatedVenditeClientiRoute: AuthenticatedVenditeClientiRoute,
  AuthenticatedVenditeProdottiRoute: AuthenticatedVenditeProdottiRoute,
  AuthenticatedAcquistiIndexRoute: AuthenticatedAcquistiIndexRoute,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  AuthRoute: AuthRoute,
  ResetPasswordRoute: ResetPasswordRoute,
  InvitoTokenRoute: InvitoTokenRoute,
  ApiPublicDaneaProductsRoute: ApiPublicDaneaProductsRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
