/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as ResetPasswordRouteImport } from './routes/reset-password'
import { Route as AuthenticatedAccountRouteImport } from './routes/_authenticated/account'
import { Route as AuthenticatedAmministrazioneRouteImport } from './routes/_authenticated/amministrazione'
import { Route as AuthenticatedB2bRouteImport } from './routes/_authenticated/b2b'
import { Route as AuthenticatedCollegamentiRouteImport } from './routes/_authenticated/collegamenti'
import { Route as AuthenticatedConsegneRouteImport } from './routes/_authenticated/consegne'
import { Route as AuthenticatedDaneaRouteImport } from './routes/_authenticated/danea'
import { Route as AuthenticatedDashboardRouteImport } from './routes/_authenticated/dashboard'
import { Route as AuthenticatedImpostazioniRouteImport } from './routes/_authenticated/impostazioni'
import { Route as AuthenticatedOnboardingRouteImport } from './routes/_authenticated/onboarding'
import { Route as AuthenticatedOperativoRouteImport } from './routes/_authenticated/operativo'
import { Route as AuthenticatedVenditeRouteImport } from './routes/_authenticated/vendite'
import { Route as ConsegnaTokenRouteImport } from './routes/consegna.$token'
import { Route as InvitoTokenRouteImport } from './routes/invito.$token'
import { Route as AuthenticatedAcquistiIndexRouteImport } from './routes/_authenticated/acquisti.index'
import { Route as AuthenticatedAcquistiFornitoriRouteImport } from './routes/_authenticated/acquisti.fornitori'
import { Route as AuthenticatedAcquistiInventarioRouteImport } from './routes/_authenticated/acquisti.inventario'
import { Route as AuthenticatedAcquistiListaSpesaRouteImport } from './routes/_authenticated/acquisti.lista-spesa'
import { Route as AuthenticatedAcquistiOrdiniRouteImport } from './routes/_authenticated/acquisti.ordini'
import { Route as AuthenticatedAcquistiProdottiRouteImport } from './routes/_authenticated/acquisti_.prodotti'
import { Route as AuthenticatedImpostazioniNavigazioneRouteImport } from './routes/_authenticated/impostazioni_.navigazione'
import { Route as AuthenticatedVenditeClientiRouteImport } from './routes/_authenticated/vendite_.clienti'
import { Route as AuthenticatedVenditeProdottiRouteImport } from './routes/_authenticated/vendite_.prodotti'
import { Route as AuthenticatedAcquistiCatalogoIndexRouteImport } from './routes/_authenticated/acquisti.catalogo.index'
import { Route as ApiPublicDaneaProductsRouteImport } from './routes/api/public/danea/products'
import { Route as LovableEmailTransactionalPreviewRouteImport } from './routes/lovable/email/transactional/preview'
import { Route as AuthenticatedAcquistiCatalogoSellerIdIndexRouteImport } from './routes/_authenticated/acquisti.catalogo.$sellerId.index'
import { Route as AuthenticatedAcquistiCatalogoSellerIdProductIdRouteImport } from './routes/_authenticated/acquisti.catalogo.$sellerId.$productId'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const ResetPasswordRoute = ResetPasswordRouteImport.update({
  id: '/reset-password',
  path: '/reset-password',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedAccountRoute = AuthenticatedAccountRouteImport.update({
  id: '/account',
  path: '/account',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedAmministrazioneRoute =
  AuthenticatedAmministrazioneRouteImport.update({
    id: '/amministrazione',
    path: '/amministrazione',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedB2bRoute = AuthenticatedB2bRouteImport.update({
  id: '/b2b',
  path: '/b2b',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedCollegamentiRoute =
  AuthenticatedCollegamentiRouteImport.update({
    id: '/collegamenti',
    path: '/collegamenti',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedConsegneRoute = AuthenticatedConsegneRouteImport.update({
  id: '/consegne',
  path: '/consegne',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedDaneaRoute = AuthenticatedDaneaRouteImport.update({
  id: '/danea',
  path: '/danea',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedDashboardRoute = AuthenticatedDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedImpostazioniRoute =
  AuthenticatedImpostazioniRouteImport.update({
    id: '/impostazioni',
    path: '/impostazioni',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedOnboardingRoute = AuthenticatedOnboardingRouteImport.update({
  id: '/onboarding',
  path: '/onboarding',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedOperativoRoute = AuthenticatedOperativoRouteImport.update({
  id: '/operativo',
  path: '/operativo',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedVenditeRoute = AuthenticatedVenditeRouteImport.update({
  id: '/vendite',
  path: '/vendite',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const ConsegnaTokenRoute = ConsegnaTokenRouteImport.update({
  id: '/consegna/$token',
  path: '/consegna/$token',
  getParentRoute: () => rootRouteImport,
} as any)
const InvitoTokenRoute = InvitoTokenRouteImport.update({
  id: '/invito/$token',
  path: '/invito/$token',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedAcquistiIndexRoute =
  AuthenticatedAcquistiIndexRouteImport.update({
    id: '/acquisti/',
    path: '/acquisti/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedAcquistiFornitoriRoute =
  AuthenticatedAcquistiFornitoriRouteImport.update({
    id: '/acquisti/fornitori',
    path: '/acquisti/fornitori',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedAcquistiInventarioRoute =
  AuthenticatedAcquistiInventarioRouteImport.update({
    id: '/acquisti/inventario',
    path: '/acquisti/inventario',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedAcquistiListaSpesaRoute =
  AuthenticatedAcquistiListaSpesaRouteImport.update({
    id: '/acquisti/lista-spesa',
    path: '/acquisti/lista-spesa',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedAcquistiOrdiniRoute =
  AuthenticatedAcquistiOrdiniRouteImport.update({
    id: '/acquisti/ordini',
    path: '/acquisti/ordini',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedAcquistiProdottiRoute =
  AuthenticatedAcquistiProdottiRouteImport.update({
    id: '/acquisti_/prodotti',
    path: '/acquisti/prodotti',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedImpostazioniNavigazioneRoute =
  AuthenticatedImpostazioniNavigazioneRouteImport.update({
    id: '/impostazioni_/navigazione',
    path: '/impostazioni/navigazione',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedVenditeClientiRoute =
  AuthenticatedVenditeClientiRouteImport.update({
    id: '/vendite_/clienti',
    path: '/vendite/clienti',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedVenditeProdottiRoute =
  AuthenticatedVenditeProdottiRouteImport.update({
    id: '/vendite_/prodotti',
    path: '/vendite/prodotti',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedAcquistiCatalogoIndexRoute =
  AuthenticatedAcquistiCatalogoIndexRouteImport.update({
    id: '/acquisti/catalogo/',
    path: '/acquisti/catalogo/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const ApiPublicDaneaProductsRoute = ApiPublicDaneaProductsRouteImport.update({
  id: '/api/public/danea/products',
  path: '/api/public/danea/products',
  getParentRoute: () => rootRouteImport,
} as any)
const LovableEmailTransactionalPreviewRoute =
  LovableEmailTransactionalPreviewRouteImport.update({
    id: '/lovable/email/transactional/preview',
    path: '/lovable/email/transactional/preview',
    getParentRoute: () => rootRouteImport,
  } as any)
const AuthenticatedAcquistiCatalogoSellerIdIndexRoute =
  AuthenticatedAcquistiCatalogoSellerIdIndexRouteImport.update({
    id: '/acquisti/catalogo/$sellerId/',
    path: '/acquisti/catalogo/$sellerId/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedAcquistiCatalogoSellerIdProductIdRoute =
  AuthenticatedAcquistiCatalogoSellerIdProductIdRouteImport.update({
    id: '/acquisti/catalogo/$sellerId/$productId',
    path: '/acquisti/catalogo/$sellerId/$productId',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/reset-password': typeof ResetPasswordRoute
  '/account': typeof AuthenticatedAccountRoute
  '/amministrazione': typeof AuthenticatedAmministrazioneRoute
  '/b2b': typeof AuthenticatedB2bRoute
  '/collegamenti': typeof AuthenticatedCollegamentiRoute
  '/consegne': typeof AuthenticatedConsegneRoute
  '/danea': typeof AuthenticatedDaneaRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/impostazioni': typeof AuthenticatedImpostazioniRoute
  '/onboarding': typeof AuthenticatedOnboardingRoute
  '/operativo': typeof AuthenticatedOperativoRoute
  '/vendite': typeof AuthenticatedVenditeRoute
  '/consegna/$token': typeof ConsegnaTokenRoute
  '/invito/$token': typeof InvitoTokenRoute
  '/acquisti/fornitori': typeof AuthenticatedAcquistiFornitoriRoute
  '/acquisti/inventario': typeof AuthenticatedAcquistiInventarioRoute
  '/acquisti/lista-spesa': typeof AuthenticatedAcquistiListaSpesaRoute
  '/acquisti/ordini': typeof AuthenticatedAcquistiOrdiniRoute
  '/acquisti/prodotti': typeof AuthenticatedAcquistiProdottiRoute
  '/impostazioni/navigazione': typeof AuthenticatedImpostazioniNavigazioneRoute
  '/vendite/clienti': typeof AuthenticatedVenditeClientiRoute
  '/vendite/prodotti': typeof AuthenticatedVenditeProdottiRoute
  '/acquisti/': typeof AuthenticatedAcquistiIndexRoute
  '/api/public/danea/products': typeof ApiPublicDaneaProductsRoute
  '/lovable/email/transactional/preview': typeof LovableEmailTransactionalPreviewRoute
  '/acquisti/catalogo/': typeof AuthenticatedAcquistiCatalogoIndexRoute
  '/acquisti/catalogo/$sellerId/$productId': typeof AuthenticatedAcquistiCatalogoSellerIdProductIdRoute
  '/acquisti/catalogo/$sellerId/': typeof AuthenticatedAcquistiCatalogoSellerIdIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/reset-password': typeof ResetPasswordRoute
  '/account': typeof AuthenticatedAccountRoute
  '/amministrazione': typeof AuthenticatedAmministrazioneRoute
  '/b2b': typeof AuthenticatedB2bRoute
  '/collegamenti': typeof AuthenticatedCollegamentiRoute
  '/consegne': typeof AuthenticatedConsegneRoute
  '/danea': typeof AuthenticatedDaneaRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/impostazioni': typeof AuthenticatedImpostazioniRoute
  '/onboarding': typeof AuthenticatedOnboardingRoute
  '/operativo': typeof AuthenticatedOperativoRoute
  '/vendite': typeof AuthenticatedVenditeRoute
  '/consegna/$token': typeof ConsegnaTokenRoute
  '/invito/$token': typeof InvitoTokenRoute
  '/acquisti/fornitori': typeof AuthenticatedAcquistiFornitoriRoute
  '/acquisti/inventario': typeof AuthenticatedAcquistiInventarioRoute
  '/acquisti/lista-spesa': typeof AuthenticatedAcquistiListaSpesaRoute
  '/acquisti/ordini': typeof AuthenticatedAcquistiOrdiniRoute
  '/acquisti/prodotti': typeof AuthenticatedAcquistiProdottiRoute
  '/impostazioni/navigazione': typeof AuthenticatedImpostazioniNavigazioneRoute
  '/vendite/clienti': typeof AuthenticatedVenditeClientiRoute
  '/vendite/prodotti': typeof AuthenticatedVenditeProdottiRoute
  '/acquisti': typeof AuthenticatedAcquistiIndexRoute
  '/api/public/danea/products': typeof ApiPublicDaneaProductsRoute
  '/lovable/email/transactional/preview': typeof LovableEmailTransactionalPreviewRoute
  '/acquisti/catalogo': typeof AuthenticatedAcquistiCatalogoIndexRoute
  '/acquisti/catalogo/$sellerId/$productId': typeof AuthenticatedAcquistiCatalogoSellerIdProductIdRoute
  '/acquisti/catalogo/$sellerId': typeof AuthenticatedAcquistiCatalogoSellerIdIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/auth': typeof AuthRoute
  '/reset-password': typeof ResetPasswordRoute
  '/_authenticated/account': typeof AuthenticatedAccountRoute
  '/_authenticated/amministrazione': typeof AuthenticatedAmministrazioneRoute
  '/_authenticated/b2b': typeof AuthenticatedB2bRoute
  '/_authenticated/collegamenti': typeof AuthenticatedCollegamentiRoute
  '/_authenticated/consegne': typeof AuthenticatedConsegneRoute
  '/_authenticated/danea': typeof AuthenticatedDaneaRoute
  '/_authenticated/dashboard': typeof AuthenticatedDashboardRoute
  '/_authenticated/impostazioni': typeof AuthenticatedImpostazioniRoute
  '/_authenticated/onboarding': typeof AuthenticatedOnboardingRoute
  '/_authenticated/operativo': typeof AuthenticatedOperativoRoute
  '/_authenticated/vendite': typeof AuthenticatedVenditeRoute
  '/consegna/$token': typeof ConsegnaTokenRoute
  '/invito/$token': typeof InvitoTokenRoute
  '/_authenticated/acquisti/fornitori': typeof AuthenticatedAcquistiFornitoriRoute
  '/_authenticated/acquisti/inventario': typeof AuthenticatedAcquistiInventarioRoute
  '/_authenticated/acquisti/lista-spesa': typeof AuthenticatedAcquistiListaSpesaRoute
  '/_authenticated/acquisti/ordini': typeof AuthenticatedAcquistiOrdiniRoute
  '/_authenticated/acquisti_/prodotti': typeof AuthenticatedAcquistiProdottiRoute
  '/_authenticated/impostazioni_/navigazione': typeof AuthenticatedImpostazioniNavigazioneRoute
  '/_authenticated/vendite_/clienti': typeof AuthenticatedVenditeClientiRoute
  '/_authenticated/vendite_/prodotti': typeof AuthenticatedVenditeProdottiRoute
  '/_authenticated/acquisti/': typeof AuthenticatedAcquistiIndexRoute
  '/api/public/danea/products': typeof ApiPublicDaneaProductsRoute
  '/lovable/email/transactional/preview': typeof LovableEmailTransactionalPreviewRoute
  '/_authenticated/acquisti/catalogo/': typeof AuthenticatedAcquistiCatalogoIndexRoute
  '/_authenticated/acquisti/catalogo/$sellerId/$productId': typeof AuthenticatedAcquistiCatalogoSellerIdProductIdRoute
  '/_authenticated/acquisti/catalogo/$sellerId/': typeof AuthenticatedAcquistiCatalogoSellerIdIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/reset-password'
    | '/account'
    | '/amministrazione'
    | '/b2b'
    | '/collegamenti'
    | '/consegne'
    | '/danea'
    | '/dashboard'
    | '/impostazioni'
    | '/onboarding'
    | '/operativo'
    | '/vendite'
    | '/consegna/$token'
    | '/invito/$token'
    | '/acquisti/fornitori'
    | '/acquisti/inventario'
    | '/acquisti/lista-spesa'
    | '/acquisti/ordini'
    | '/acquisti/prodotti'
    | '/impostazioni/navigazione'
    | '/vendite/clienti'
    | '/vendite/prodotti'
    | '/acquisti/'
    | '/api/public/danea/products'
    | '/lovable/email/transactional/preview'
    | '/acquisti/catalogo/'
    | '/acquisti/catalogo/$sellerId/$productId'
    | '/acquisti/catalogo/$sellerId/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/reset-password'
    | '/account'
    | '/amministrazione'
    | '/b2b'
    | '/collegamenti'
    | '/consegne'
    | '/danea'
    | '/dashboard'
    | '/impostazioni'
    | '/onboarding'
    | '/operativo'
    | '/vendite'
    | '/consegna/$token'
    | '/invito/$token'
    | '/acquisti/fornitori'
    | '/acquisti/inventario'
    | '/acquisti/lista-spesa'
    | '/acquisti/ordini'
    | '/acquisti/prodotti'
    | '/impostazioni/navigazione'
    | '/vendite/clienti'
    | '/vendite/prodotti'
    | '/acquisti'
    | '/api/public/danea/products'
    | '/lovable/email/transactional/preview'
    | '/acquisti/catalogo'
    | '/acquisti/catalogo/$sellerId/$productId'
    | '/acquisti/catalogo/$sellerId'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/auth'
    | '/reset-password'
    | '/_authenticated/account'
    | '/_authenticated/amministrazione'
    | '/_authenticated/b2b'
    | '/_authenticated/collegamenti'
    | '/_authenticated/consegne'
    | '/_authenticated/danea'
    | '/_authenticated/dashboard'
    | '/_authenticated/impostazioni'
    | '/_authenticated/onboarding'
    | '/_authenticated/operativo'
    | '/_authenticated/vendite'
    | '/consegna/$token'
    | '/invito/$token'
    | '/_authenticated/acquisti/fornitori'
    | '/_authenticated/acquisti/inventario'
    | '/_authenticated/acquisti/lista-spesa'
    | '/_authenticated/acquisti/ordini'
    | '/_authenticated/acquisti_/prodotti'
    | '/_authenticated/impostazioni_/navigazione'
    | '/_authenticated/vendite_/clienti'
    | '/_authenticated/vendite_/prodotti'
    | '/_authenticated/acquisti/'
    | '/api/public/danea/products'
    | '/lovable/email/transactional/preview'
    | '/_authenticated/acquisti/catalogo/'
    | '/_authenticated/acquisti/catalogo/$sellerId/$productId'
    | '/_authenticated/acquisti/catalogo/$sellerId/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  AuthRoute: typeof AuthRoute
  ResetPasswordRoute: typeof ResetPasswordRoute
  ConsegnaTokenRoute: typeof ConsegnaTokenRoute
  InvitoTokenRoute: typeof InvitoTokenRoute
  ApiPublicDaneaProductsRoute: typeof ApiPublicDaneaProductsRoute
  LovableEmailTransactionalPreviewRoute: typeof LovableEmailTransactionalPreviewRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reset-password': {
      id: '/reset-password'
      path: '/reset-password'
      fullPath: '/reset-password'
      preLoaderRoute: typeof ResetPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/account': {
      id: '/_authenticated/account'
      path: '/account'
      fullPath: '/account'
      preLoaderRoute: typeof AuthenticatedAccountRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/amministrazione': {
      id: '/_authenticated/amministrazione'
      path: '/amministrazione'
      fullPath: '/amministrazione'
      preLoaderRoute: typeof AuthenticatedAmministrazioneRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/b2b': {
      id: '/_authenticated/b2b'
      path: '/b2b'
      fullPath: '/b2b'
      preLoaderRoute: typeof AuthenticatedB2bRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/collegamenti': {
      id: '/_authenticated/collegamenti'
      path: '/collegamenti'
      fullPath: '/collegamenti'
      preLoaderRoute: typeof AuthenticatedCollegamentiRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/consegne': {
      id: '/_authenticated/consegne'
      path: '/consegne'
      fullPath: '/consegne'
      preLoaderRoute: typeof AuthenticatedConsegneRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/danea': {
      id: '/_authenticated/danea'
      path: '/danea'
      fullPath: '/danea'
      preLoaderRoute: typeof AuthenticatedDaneaRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/dashboard': {
      id: '/_authenticated/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof AuthenticatedDashboardRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/impostazioni': {
      id: '/_authenticated/impostazioni'
      path: '/impostazioni'
      fullPath: '/impostazioni'
      preLoaderRoute: typeof AuthenticatedImpostazioniRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/onboarding': {
      id: '/_authenticated/onboarding'
      path: '/onboarding'
      fullPath: '/onboarding'
      preLoaderRoute: typeof AuthenticatedOnboardingRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/operativo': {
      id: '/_authenticated/operativo'
      path: '/operativo'
      fullPath: '/operativo'
      preLoaderRoute: typeof AuthenticatedOperativoRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/vendite': {
      id: '/_authenticated/vendite'
      path: '/vendite'
      fullPath: '/vendite'
      preLoaderRoute: typeof AuthenticatedVenditeRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/consegna/$token': {
      id: '/consegna/$token'
      path: '/consegna/$token'
      fullPath: '/consegna/$token'
      preLoaderRoute: typeof ConsegnaTokenRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/invito/$token': {
      id: '/invito/$token'
      path: '/invito/$token'
      fullPath: '/invito/$token'
      preLoaderRoute: typeof InvitoTokenRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/acquisti/': {
      id: '/_authenticated/acquisti/'
      path: '/acquisti'
      fullPath: '/acquisti/'
      preLoaderRoute: typeof AuthenticatedAcquistiIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/acquisti/fornitori': {
      id: '/_authenticated/acquisti/fornitori'
      path: '/acquisti/fornitori'
      fullPath: '/acquisti/fornitori'
      preLoaderRoute: typeof AuthenticatedAcquistiFornitoriRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/acquisti/inventario': {
      id: '/_authenticated/acquisti/inventario'
      path: '/acquisti/inventario'
      fullPath: '/acquisti/inventario'
      preLoaderRoute: typeof AuthenticatedAcquistiInventarioRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/acquisti/lista-spesa': {
      id: '/_authenticated/acquisti/lista-spesa'
      path: '/acquisti/lista-spesa'
      fullPath: '/acquisti/lista-spesa'
      preLoaderRoute: typeof AuthenticatedAcquistiListaSpesaRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/acquisti/ordini': {
      id: '/_authenticated/acquisti/ordini'
      path: '/acquisti/ordini'
      fullPath: '/acquisti/ordini'
      preLoaderRoute: typeof AuthenticatedAcquistiOrdiniRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/acquisti_/prodotti': {
      id: '/_authenticated/acquisti_/prodotti'
      path: '/acquisti/prodotti'
      fullPath: '/acquisti/prodotti'
      preLoaderRoute: typeof AuthenticatedAcquistiProdottiRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/impostazioni_/navigazione': {
      id: '/_authenticated/impostazioni_/navigazione'
      path: '/impostazioni/navigazione'
      fullPath: '/impostazioni/navigazione'
      preLoaderRoute: typeof AuthenticatedImpostazioniNavigazioneRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/vendite_/clienti': {
      id: '/_authenticated/vendite_/clienti'
      path: '/vendite/clienti'
      fullPath: '/vendite/clienti'
      preLoaderRoute: typeof AuthenticatedVenditeClientiRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/vendite_/prodotti': {
      id: '/_authenticated/vendite_/prodotti'
      path: '/vendite/prodotti'
      fullPath: '/vendite/prodotti'
      preLoaderRoute: typeof AuthenticatedVenditeProdottiRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/acquisti/catalogo/': {
      id: '/_authenticated/acquisti/catalogo/'
      path: '/acquisti/catalogo'
      fullPath: '/acquisti/catalogo/'
      preLoaderRoute: typeof AuthenticatedAcquistiCatalogoIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/api/public/danea/products': {
      id: '/api/public/danea/products'
      path: '/api/public/danea/products'
      fullPath: '/api/public/danea/products'
      preLoaderRoute: typeof ApiPublicDaneaProductsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/lovable/email/transactional/preview': {
      id: '/lovable/email/transactional/preview'
      path: '/lovable/email/transactional/preview'
      fullPath: '/lovable/email/transactional/preview'
      preLoaderRoute: typeof LovableEmailTransactionalPreviewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/acquisti/catalogo/$sellerId/': {
      id: '/_authenticated/acquisti/catalogo/$sellerId/'
      path: '/acquisti/catalogo/$sellerId'
      fullPath: '/acquisti/catalogo/$sellerId/'
      preLoaderRoute: typeof AuthenticatedAcquistiCatalogoSellerIdIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/acquisti/catalogo/$sellerId/$productId': {
      id: '/_authenticated/acquisti/catalogo/$sellerId/$productId'
      path: '/acquisti/catalogo/$sellerId/$productId'
      fullPath: '/acquisti/catalogo/$sellerId/$productId'
      preLoaderRoute: typeof AuthenticatedAcquistiCatalogoSellerIdProductIdRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
  }
}

interface AuthenticatedRouteRouteChildren {
  AuthenticatedAccountRoute: typeof AuthenticatedAccountRoute
  AuthenticatedAmministrazioneRoute: typeof AuthenticatedAmministrazioneRoute
  AuthenticatedB2bRoute: typeof AuthenticatedB2bRoute
  AuthenticatedCollegamentiRoute: typeof AuthenticatedCollegamentiRoute
  AuthenticatedConsegneRoute: typeof AuthenticatedConsegneRoute
  AuthenticatedDaneaRoute: typeof AuthenticatedDaneaRoute
  AuthenticatedDashboardRoute: typeof AuthenticatedDashboardRoute
  AuthenticatedImpostazioniRoute: typeof AuthenticatedImpostazioniRoute
  AuthenticatedOnboardingRoute: typeof AuthenticatedOnboardingRoute
  AuthenticatedOperativoRoute: typeof AuthenticatedOperativoRoute
  AuthenticatedVenditeRoute: typeof AuthenticatedVenditeRoute
  AuthenticatedAcquistiFornitoriRoute: typeof AuthenticatedAcquistiFornitoriRoute
  AuthenticatedAcquistiInventarioRoute: typeof AuthenticatedAcquistiInventarioRoute
  AuthenticatedAcquistiListaSpesaRoute: typeof AuthenticatedAcquistiListaSpesaRoute
  AuthenticatedAcquistiOrdiniRoute: typeof AuthenticatedAcquistiOrdiniRoute
  AuthenticatedAcquistiProdottiRoute: typeof AuthenticatedAcquistiProdottiRoute
  AuthenticatedImpostazioniNavigazioneRoute: typeof AuthenticatedImpostazioniNavigazioneRoute
  AuthenticatedVenditeClientiRoute: typeof AuthenticatedVenditeClientiRoute
  AuthenticatedVenditeProdottiRoute: typeof AuthenticatedVenditeProdottiRoute
  AuthenticatedAcquistiIndexRoute: typeof AuthenticatedAcquistiIndexRoute
  AuthenticatedAcquistiCatalogoIndexRoute: typeof AuthenticatedAcquistiCatalogoIndexRoute
  AuthenticatedAcquistiCatalogoSellerIdProductIdRoute: typeof AuthenticatedAcquistiCatalogoSellerIdProductIdRoute
  AuthenticatedAcquistiCatalogoSellerIdIndexRoute: typeof AuthenticatedAcquistiCatalogoSellerIdIndexRoute
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedAccountRoute: AuthenticatedAccountRoute,
  AuthenticatedAmministrazioneRoute: AuthenticatedAmministrazioneRoute,
  AuthenticatedB2bRoute: AuthenticatedB2bRoute,
  AuthenticatedCollegamentiRoute: AuthenticatedCollegamentiRoute,
  AuthenticatedConsegneRoute: AuthenticatedConsegneRoute,
  AuthenticatedDaneaRoute: AuthenticatedDaneaRoute,
  AuthenticatedDashboardRoute: AuthenticatedDashboardRoute,
  AuthenticatedImpostazioniRoute: AuthenticatedImpostazioniRoute,
  AuthenticatedOnboardingRoute: AuthenticatedOnboardingRoute,
  AuthenticatedOperativoRoute: AuthenticatedOperativoRoute,
  AuthenticatedVenditeRoute: AuthenticatedVenditeRoute,
  AuthenticatedAcquistiFornitoriRoute: AuthenticatedAcquistiFornitoriRoute,
  AuthenticatedAcquistiInventarioRoute: AuthenticatedAcquistiInventarioRoute,
  AuthenticatedAcquistiListaSpesaRoute: AuthenticatedAcquistiListaSpesaRoute,
  AuthenticatedAcquistiOrdiniRoute: AuthenticatedAcquistiOrdiniRoute,
  AuthenticatedAcquistiProdottiRoute: AuthenticatedAcquistiProdottiRoute,
  AuthenticatedImpostazioniNavigazioneRoute:
    AuthenticatedImpostazioniNavigazioneRoute,
  AuthenticatedVenditeClientiRoute: AuthenticatedVenditeClientiRoute,
  AuthenticatedVenditeProdottiRoute: AuthenticatedVenditeProdottiRoute,
  AuthenticatedAcquistiIndexRoute: AuthenticatedAcquistiIndexRoute,
  AuthenticatedAcquistiCatalogoIndexRoute:
    AuthenticatedAcquistiCatalogoIndexRoute,
  AuthenticatedAcquistiCatalogoSellerIdProductIdRoute:
    AuthenticatedAcquistiCatalogoSellerIdProductIdRoute,
  AuthenticatedAcquistiCatalogoSellerIdIndexRoute:
    AuthenticatedAcquistiCatalogoSellerIdIndexRoute,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  AuthRoute: AuthRoute,
  ResetPasswordRoute: ResetPasswordRoute,
  ConsegnaTokenRoute: ConsegnaTokenRoute,
  InvitoTokenRoute: InvitoTokenRoute,
  ApiPublicDaneaProductsRoute: ApiPublicDaneaProductsRoute,
  LovableEmailTransactionalPreviewRoute: LovableEmailTransactionalPreviewRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
